import { categories, products } from './products.js';
const root = document.querySelector('#app');
const whatsappNumber = '919307676833';
let cart = JSON.parse(localStorage.getItem('craftvilla-cart') || '{}');
let modalProduct = null;
const money = (value) => `₹${value}`;
const escapeHtml = (value) => String(value).replace(/[&<>"]/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const cartItems = () => Object.entries(cart).map(([id, qty]) => ({...products.find((product) => product.id === id), qty})).filter((item) => item.id);
const saveCart = () => localStorage.setItem('craftvilla-cart', JSON.stringify(cart));
const logo = () => `<div class="logo-badge"><span class="logo-bow">୨୧</span><strong>Craft<br>Villa</strong><small>Handmade with Love</small></div>`;
const imageCard = (product, large = false) => `<div class="product-art ${large ? 'large' : ''}" style="--tone-a:${product.theme[0]};--tone-b:${product.theme[1]}"><i></i><span>${product.theme[2]}</span><em>${escapeHtml(product.category)}</em></div>`;
const card = (product) => `<article class="product-card"><button class="art-button" data-open="${product.id}">${imageCard(product)}</button><div class="product-copy"><p class="tag">${escapeHtml(product.category)}</p><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.description)}</p><div class="buy-row"><strong>${money(product.price)}</strong><button data-add="${product.id}">Add</button></div></div></article>`;
function frame(content) { const count = cartItems().reduce((sum, item) => sum + item.qty, 0); return `<header><a class="brand" href="#/">${logo()}<span>CraftVilla</span></a><nav id="nav"><a href="#/">Home</a>${categories.map((category) => `<a href="#/shop/${encodeURIComponent(category)}">${category}</a>`).join('')}<a class="bag" href="#/cart">Bag (${count})</a></nav><button id="menu" class="menu">☰</button></header><main>${content}</main><footer>${logo()}<p>Handmade with Love, Made Just for You.</p><a href="https://instagram.com/Craftvilla_in">📷 @Craftvilla_in</a><a href="tel:+919307676833">☎ +91 9307676833</a><small>© 2026 CraftVilla by Janvi Agrawal</small></footer>${modalProduct ? modal(modalProduct) : ''}`; }
function shopPage() { const category = decodeURIComponent((location.hash || '#/').replace('#/shop/', '')); const shown = categories.includes(category) ? products.filter((product) => product.category === category) : products; return `<section class="hero"><div><p class="eyebrow">✦ By Janvi Agrawal</p><h1>Handmade with Love, Made Just for You.</h1><p>Gift hampers and handcrafted accessories with soft florals, thoughtful details, and a boutique finish.</p><div class="hero-actions"><a href="#/shop/Gift%20Hampers">Shop Hampers</a><a class="secondary" href="#/shop/Handmade%20Accessories">Accessories</a></div></div>${logo()}</section><section class="rakhi"><b>Rakhi Collection is Here 🎀</b><span>Maroon-and-gold festive picks for siblings, cousins, and sweet little surprises.</span></section><section class="category-tiles">${categories.map((item) => `<a href="#/shop/${encodeURIComponent(item)}"><span>${item === 'Gift Hampers' ? '🎁' : '🌸'}</span><b>${item}</b><small>${products.filter((product) => product.category === item).length} handmade picks</small></a>`).join('')}</section><section class="about"><h2>About CraftVilla</h2><p>Janvi creates every piece with a personal, gift-worthy touch — from pastel cup hampers to playful floral keychains and headbands.</p></section><section class="catalog"><div class="section-head"><h2>${categories.includes(category) ? category : 'Featured Products'}</h2><div class="tabs">${categories.map((item) => `<a class="${category === item ? 'active' : ''}" href="#/shop/${encodeURIComponent(item)}">${item}</a>`).join('')}</div></div><div class="grid">${shown.map(card).join('')}</div></section>`; }
function modal(product) { return `<div class="modal"><article><button class="close" data-close>×</button>${imageCard(product, true)}<p class="tag">${escapeHtml(product.category)}</p><h2>${escapeHtml(product.name)}</h2><strong class="modal-price">${money(product.price)}</strong><p>${escapeHtml(product.description)}</p><div class="qty"><button data-dec>−</button><span id="modalQty">1</span><button data-inc>+</button></div><button class="checkout-button" data-modal-add="${product.id}">Add to Cart</button></article></div>`; }
function cartPage() { const items = cartItems(); const subtotal = items.reduce((sum, item) => sum + item.price * item.qty, 0); if (!items.length) return `<section class="cart-page"><h1>Your CraftVilla Bag</h1><p class="empty">Your bag is waiting for something handmade. <a href="#/shop/Gift%20Hampers">Start shopping</a>.</p></section>`; return `<section class="cart-page"><h1>Your CraftVilla Bag</h1><div class="cart-list">${items.map((item) => `<article>${imageCard(item)}<div><h3>${escapeHtml(item.name)}</h3><p>${money(item.price)} each</p><div class="qty compact"><button data-qty="${item.id}" data-next="${item.qty - 1}">−</button><span>${item.qty}</span><button data-qty="${item.id}" data-next="${item.qty + 1}">+</button><button class="remove" data-qty="${item.id}" data-next="0">Remove</button></div></div><strong>${money(item.price * item.qty)}</strong></article>`).join('')}</div><section class="checkout"><h2>Subtotal: ${money(subtotal)}</h2><p>Share your details and checkout via WhatsApp. Janvi will confirm payment manually via UPI.</p><form id="checkout"><input name="name" required placeholder="Your name"><input name="phone" required placeholder="Phone number"><textarea name="address" required placeholder="Delivery address"></textarea><button class="checkout-button">Checkout via WhatsApp</button></form></section></section>`; }
function render() { root.innerHTML = frame(location.hash.startsWith('#/cart') ? cartPage() : shopPage()); bindEvents(); }
function bindEvents() { document.querySelector('#menu')?.addEventListener('click', () => document.querySelector('#nav').classList.toggle('open')); document.querySelectorAll('[data-add]').forEach((button) => button.addEventListener('click', () => { cart[button.dataset.add] = (cart[button.dataset.add] || 0) + 1; saveCart(); render(); })); document.querySelectorAll('[data-open]').forEach((button) => button.addEventListener('click', () => { modalProduct = products.find((product) => product.id === button.dataset.open); render(); })); document.querySelector('[data-close]')?.addEventListener('click', () => { modalProduct = null; render(); }); let modalQty = 1; document.querySelector('[data-inc]')?.addEventListener('click', () => { modalQty += 1; document.querySelector('#modalQty').textContent = modalQty; }); document.querySelector('[data-dec]')?.addEventListener('click', () => { modalQty = Math.max(1, modalQty - 1); document.querySelector('#modalQty').textContent = modalQty; }); document.querySelector('[data-modal-add]')?.addEventListener('click', (event) => { for (let count = 0; count < modalQty; count += 1) cart[event.target.dataset.modalAdd] = (cart[event.target.dataset.modalAdd] || 0) + 1; modalProduct = null; saveCart(); render(); }); document.querySelectorAll('[data-qty]').forEach((button) => button.addEventListener('click', () => { const next = Number(button.dataset.next); if (next <= 0) delete cart[button.dataset.qty]; else cart[button.dataset.qty] = next; saveCart(); render(); })); document.querySelector('#checkout')?.addEventListener('submit', (event) => { event.preventDefault(); const details = Object.fromEntries(new FormData(event.target)); if (!/^[0-9+\-\s]{10,15}$/.test(details.phone.trim())) return alert('Please enter a valid phone number.'); const orderItems = cartItems(); const subtotal = orderItems.reduce((sum, item) => sum + item.price * item.qty, 0); const message = ['Hello Janvi, I would like to place this CraftVilla order:', '', ...orderItems.map((item) => `• ${item.name} x ${item.qty} = ${money(item.price * item.qty)}`), '', `Subtotal: ${money(subtotal)}`, '', `Name: ${details.name}`, `Phone: ${details.phone}`, `Delivery Address: ${details.address}`].join('\n'); window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer'); }); }
addEventListener('hashchange', render);
render();
