export const categories = ['Gift Hampers', 'Handmade Accessories'];
export const products = [
 {id:'pastel-ribbon-cup-hamper-blue',category:'Gift Hampers',name:'Pastel Ribbon Cup Hamper – Blue',price:299,description:'A dreamy clear cup hamper wrapped in a teal satin bow, filled with a soft scrunchie, delicate jewelry pieces, and shredded paper filling. A sweet surprise-in-a-cup for any occasion.',theme:['#80c7c8','#f8e6df','🎁']},
 {id:'pastel-ribbon-cup-hamper-gold',category:'Gift Hampers',name:'Pastel Ribbon Cup Hamper – Gold',price:299,description:'Same lovely cup-hamper format in warm golden tones, with a mustard scrunchie and matching ribbon bow.',theme:['#d9a441','#fff5d8','🎀']},
 {id:'pastel-ribbon-cup-hamper-pink',category:'Gift Hampers',name:'Pastel Ribbon Cup Hamper – Pink',price:299,description:'A hot-pink ribboned cup hamper with a blush scrunchie and delicate jewelry inside.',theme:['#e979a8','#ffe1ec','💝']},
 {id:'evil-eye-rakhi-chocolate-box',category:'Gift Hampers',name:'Evil-Eye Rakhi Chocolate Box',price:349,description:'A protective, playful hamper featuring Cadbury Dairy Milk bars, Gems, and evil-eye charm cutouts wishing "Happy Raksha Bandhan" — as sweet as it is symbolic.',theme:['#244c86','#f7d469','🧿']},
 {id:'rakshabandhan-atm-hamper',category:'Gift Hampers',name:'Rakshabandhan ATM Hamper',price:499,description:'A novelty "ATM"-themed snack box loaded with chips, chocolates, and treats — a full withdrawal of love this Rakhi.',theme:['#8f2637','#f4c75d','🏧']},
 {id:'dairy-milk-heart-bouquet',category:'Gift Hampers',name:'Dairy Milk Heart Bouquet',price:349,description:'Six Cadbury Dairy Milk bars arranged into a heart, framed with baby\'s breath and a cream satin bow. Small, sweet, and special.',theme:['#6f4bb2','#fff0d6','💜']},
 {id:'golden-heart-rakhi-box',category:'Gift Hampers',name:'Golden Heart Rakhi Box',price:399,description:'A glass-panelled gift box in gold, tied with a lavender ribbon, filled with Dairy Milk, 5 Star, Gems, and a flower keychain charm.',theme:['#c79534','#ded0ff','💛']},
 {id:'candy-lollipop-bouquet',category:'Gift Hampers',name:'Candy Lollipop Bouquet',price:379,description:'A giant lollipop-shaped bundle of candies, wafers, and chocolates wrapped in cellophane with a polka-dot bow.',theme:['#ff7bac','#b7e7ec','🍭']},
 {id:'golden-rose-tulle-snack-basket',category:'Gift Hampers',name:'Golden Rose Tulle Snack Basket',price:449,description:'A generous snack basket wrapped in gold tulle netting, finished with a satin rose and glitter leaves.',theme:['#d6a74f','#fff2c7','🌹']},
 {id:'pink-bow-hair-clips',category:'Handmade Accessories',name:'Pink Bow Hair Clips (Set of 2)',price:99,description:'Hand-twisted pipe-cleaner bows with pearl centers on sleek hair clips.',theme:['#f096b6','#fff1f6','🎀']},
 {id:'pink-purple-flower-bouquet-keychain',category:'Handmade Accessories',name:'Pink & Purple Flower Bouquet Keychain',price:129,description:'A tiny hand-shaped flower bouquet finished with an organza ribbon bow.',theme:['#b487d9','#ffe1ef','💐']},
 {id:'heart-crown-headband-set',category:'Handmade Accessories',name:'Heart & Crown Headband Set (2 pcs)',price:149,description:'A whimsical pair — a heart-topped wand and a crown headband — handcrafted in pipe cleaner with fabric detailing.',theme:['#f49bbb','#f9d25f','👑']},
 {id:'tri-colour-flower-bangle',category:'Handmade Accessories',name:'Tri-Colour Flower Bangle (Set of 2)',price:129,description:'Saffron and green floral bangles with pearl accents.',theme:['#f4993a','#6fa66f','🌼']},
 {id:'bunny-ears-floral-headband-pink',category:'Handmade Accessories',name:'Bunny Ears Floral Headband – Pink',price:149,description:'A playful pink bunny-ear headband with a hand-shaped flower accent.',theme:['#f4a1bd','#fff4fa','🐰']},
 {id:'sunflower-headband-yellow',category:'Handmade Accessories',name:'Sunflower Headband – Yellow',price:149,description:'A row of hand-crafted sunflowers along a green pipe-cleaner headband.',theme:['#f6c63d','#87b96e','🌻']},
 {id:'wildflower-headband-purple-white',category:'Handmade Accessories',name:'Wildflower Headband – Purple & White',price:149,description:'Soft mixed purple-and-white blossom headband.',theme:['#9f7dd2','#faf7ff','🌸']},
 {id:'pink-bow-keychain',category:'Handmade Accessories',name:'Pink Bow Keychain',price:89,description:'A dainty pearl-centered bow keychain.',theme:['#f38cb2','#fff5f9','🎀']},
 {id:'lollipop-swirl-keychain-teal-purple',category:'Handmade Accessories',name:'Lollipop Swirl Keychain – Teal & Purple',price:99,description:'A whimsical swirl-lollipop-shaped keychain.',theme:['#48bfd0','#a87bd6','🍬']},
 {id:'green-bow-tulip-keychain',category:'Handmade Accessories',name:'Green Bow Tulip Keychain',price:99,description:'A tulip bouquet keychain finished with a green bow.',theme:['#6fa66f','#f3a0b6','🌷']},
 {id:'pink-purple-flower-wreath-keychain',category:'Handmade Accessories',name:'Pink & Purple Flower Wreath Keychain',price:109,description:'A circular wreath of blush and lilac blooms with pearl centers.',theme:['#e99dbc','#b88bd8','🌺']},
 {id:'blue-teal-flower-cluster-keychain',category:'Handmade Accessories',name:'Blue-Teal Flower Cluster Keychain',price:89,description:'A cluster of teal and blue blossoms with pearl centers.',theme:['#53bdd0','#4d8fc9','💠']}
];
